### ISSUE TITLE
Can’t access to translation panel

### ISSUE THREAD

**Issue by JeremDigi** [sanity-io/document-internationalization#22]
Hello, 

When I try to access to "translations" panel in my document, I have an error : 

`Cannot read properties of undefined (reading 'replace')`

My configuration:
```js
// deskStructure.js
import * as Structure from '@sanity/document-internationalization/lib/structure'

export const getDefaultDocumentNode = Structure.getDefaultDocumentNode
export default Structure.default
```
```js
// document-internationalization.json
{
    "idStructure": "delimiter",
    "referenceBehavior": "strong",
    "languages": [
      [{"id": "en", "title": "English"}],
      [{"id": "fr", "title": "French"}]
    ]
}
```
```js
// schemas/post.js
export default {
  name: "post",
  title: "Articles",
  type: "document",
  i18n: true,
  fields: [
    {
      name: "title",
      title: "Titre",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
          source: 'title'
      },
      validation: (Rule) => Rule.required(),
    },
    
  ],
  initialValue: {
    __i18n_lang: 'fr',
  },
};
```

Full error :
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at http://localhost:3333/static/js/app.bundle.js:296766:24
    at mountMemo (/static/js/vendor.bundle.js:18584:19)
    at Object.useMemo (/static/js/vendor.bundle.js:18880:16)
    at useMemo (/static/js/vendor.bundle.js:2327:21)
    at Object.wrappedHook [as useMemo] (/static/js/app.bundle.js:386235:14)
    at LangCultureFlagsBlock (/static/js/app.bundle.js:296765:58)
    at renderWithHooks (/static/js/vendor.bundle.js:17945:18)
    at mountIndeterminateComponent (/static/js/vendor.bundle.js:20624:13)
    at beginWork (/static/js/vendor.bundle.js:21738:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3330:14)
```

Did I do something wrong?

Thank you

**Comment by JeremDigi** [comment]
After some tests, the problem only appears when I define the languages like this:

```json
"languages": [
      [{"id": "fr", "title": "French"}],
      [{"id": "en", "title": "English"}]
 ]
```

If I declare the languages like this, I have no problems:

```json
"languages": ["fr", "en"]
```

**Comment by iksi** [comment]
@JeremDigi It seems that the documentation is wrong and you need to declare the languages as follows:

```js
"languages": [
      {"id": "fr", "title": "French"},
      {"id": "en", "title": "English"}
 ]
```

**Comment by LiamMartens** [comment]
@iksi @JeremDigi you're right the docs had a typo where the languages list was an array of arrays which is not correct. I have fixed the docs now.
